version: '3.8'

services:
  frontend:
    build:
      context: ./frontend   # Path to the frontend directory
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL : localhost:5000
    ports:
      - "5173:80"             # Expose the React app on port 5173(default vite)
    
    depends_on:
      - backend             # Waits for the backend to be ready

  backend:
    build:
      context: ./backend
    environment:
      - DB_URL=postgresql://db_user:db_password@db:5432/postgres
      - PORT=5000
    ports:
      - "5000:5000"  # Backend accessible on port 5000
    depends_on:
      - db  # Ensure database is ready before the backend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"         # Expose the PostgreSQL database on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data

volumes:
  postgres_data:
    driver: local
